### ISSUE TITLE
How about v3.0.17 ?

### ISSUE THREAD

**Issue by ammoniak** [webjars/angular-bootstrap-colorpicker#1]
There were quite a few bug fixed in the recent versions. An update for the newest version would be nice. Either the Bower or the classic version :-)

**Comment by jamesward** [comment]
FYI: You can deploy Bower WebJars yourself.

The Classic WebJar for this version will be released shortly.

**Comment by ammoniak** [comment]
Thanks for the quick response time. I prefer the classic WebJar, so I'm completely happy now ;-)
